apiVersion: v1
kind: Service
metadata:
  name: {{ include "stats.fullname" . }}-svc
  labels:
    helm.sh/chart: {{ include "library-app.chart" . }}
    {{- include "stats.selectorLabels" . |  nindent 4}}
  namespace: {{ include "library-app.namespace" . }}
spec:
  type: {{ .Values.stats.service.type }}
  ports:
    - port: {{ .Values.stats.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "stats.selectorLabels" . | nindent 4 }}
