apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reservation.fullname" . }}-secret
  labels:
    helm.sh/chart: {{ include "library-app.chart" . }}
    {{- include "reservation.selectorLabels" . | nindent 4 }}
  namespace: {{ include "library-app.namespace" . }}
type: Opaque
stringData:
  db-pass: "{{ .Values.db.secret.pass}}"