apiVersion: v1
kind: Secret
metadata:
  name: {{ include "library.fullname" . }}-secret
  labels:
    {{- include "library-app.labels" . | nindent 4 }}
  namespace: {{ include "library-app.namespace" . }}
type: Opaque
stringData:
  db-pass: "{{ .Values.db.secret.pass}}"