apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "provider.fullname" . }}-config
  labels:
    {{- include "library-app.labels" . | nindent 4 }}
  namespace: {{ include "library-app.namespace" . }}
data:
  HTTP_HOST:  "{{ .Values.configData.provider.http.host }}"
  HTTP_PORT: {{ .Values.configData.provider.http.port | quote }}
  HTTP_READ: {{ .Values.configData.provider.http.read | quote }}
  DB_HOST: "{{ .Values.configData.db.host }}"
  DB_PORT: "{{ .Values.configData.db.port  }}"
  DB_USER: "{{ .Values.configData.db.user }}"
  DB_NAME: "{{ .Values.configData.provider.dbName }}"
