{{- if .Values.db.service.ip.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "db.name" . }}-ip
  labels:
    {{- include "db.labels" . | nindent 4 }}
  namespace: {{ include "library-app.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  type: {{ .Values.db.service.ip.type }}
  ports:
    - port: {{ .Values.db.service.lb.port }}
      targetPort: {{ .Values.db.portName }}
      protocol: TCP
  selector:
    {{- include "db.selectorLabels" . | nindent 4 }}
{{- end}}