apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}-config
  labels:
    {{- include "library-app.labels" . | nindent 4 }}
  namespace: {{ include "library-app.namespace" . }}
data:
  HTTP_HOST:  "{{ .Values.configData.gateway.http.host }}"
  HTTP_PORT: "{{ .Values.configData.gateway.http.port }}"
  HTTP_READ: "{{ .Values.configData.gateway.http.read }}"
  LIBRARY_HTTP_HOST: "{{ .Values.configData.gateway.services.libraryHost}}"
  RESERVATION_HTTP_HOST: "{{ .Values.configData.gateway.services.reservationHost}}"
  RATING_HTTP_HOST: "{{ .Values.configData.gateway.services.ratingHost}}"
  DB_HOST: "{{ .Values.configData.db.host }}"
  DB_PORT: "{{ .Values.configData.db.port  }}"
  DB_USER: "{{ .Values.configData.db.user }}"
  DB_NAME: "{{ .Values.configData.db.name }}"
  AUTH0_DOMAIN: "{{ .Values.gateway.auth0.domain}}"
  AUTH0_AUDIENCE: "{{ .Values.gateway.auth0.audience}}"
